version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: portAndAdapters
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: database
    ports:
      - "5431:5432"
